name: Node.js CI
on: [pull_request]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        working-directory: ./server
        run: npm install
      - name: npm test
        working-directory: ./server
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb+srv://resthub-admin:resthub-admin@resthub-sg.udsmr.mongodb.net/resthub?retryWrites=true&w=majority
        run: npm test