name: Test Automation
on: [push, pull_request]
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - run: npm cache clean -f
      - run: rm -rf node_modules
      - run: npm i
      - run: npm test